### ISSUE TITLE
Issues instantiating client using v5.0.0.

### ISSUE THREAD

**Issue by sergidt** [stomp-js/stompjs#17]
I was working with the version 5.0.0.-beta.4 under an angular project, and my code works successfully.

The same code is crashing since I have updated my package.json in order to use the latest released version 5.0.0.)

this is the error I get: 
```
core.js:1673 ERROR TypeError: Cannot set property 'binaryType' of null
    at Client.push../node_modules/@stomp/stompjs/esm5/client.js.Client._createWebSocket (client.js:175)
    at Client.push../node_modules/@stomp/stompjs/esm5/client.js.Client._connect (client.js:125)
    at Client.push../node_modules/@stomp/stompjs/esm5/client.js.Client.activate (client.js:110)
```

can anybody help me?

**Comment by kum-deepak** [comment]
Please share all the configuration options you are setting. Also let me know which broker you are using?

There is one change which might have affected your code, need to know the above details to narrow down.

**Comment by sergidt** [comment]
the broker is stampy.

my config is: 

```
this.client = new Stomp.Client({
                connectHeaders: {
                    login: null,
                    passcode: null,
                    host: generateUID()
                },
                heartbeatIncoming: HEARTBEAT_INCOMING,
                heartbeatOutgoing: HEARTBEAT_OUTGOING,
                reconnectDelay: RECONNECT_DELAY,
                debug: () => null,
                webSocketFactory: () => null,
                onConnect: () => observer.next(PubSubState.CONNECTED),
                onUnhandledFrame: this.frameErrorHandler,
                onStompError: this.frameErrorHandler,
                onDisconnect: this.disconnectionHandler,
                onWebSocketClose: () => observer.next(PubSubState.CLOSED),
                beforeConnect: this.beforeWSConnectionHandler
            });
```

Am I missing something?

**Comment by kum-deepak** [comment]
What is your broker address?

The following seems incorrect:

```typescript
    webSocketFactory: () => null
```

Please see: https://stomp-js.github.io/stompjs/classes/Client.html#webSocketFactory and https://stomp-js.github.io/stompjs/classes/Client.html#brokerURL

**Comment by sergidt** [comment]
I am defining my brokerUrl inside the beforeConnect, because my broker url has a jwt token and changes every several minutes (security reasons).

Is not true?

This approach worked with beta version

**Comment by kum-deepak** [comment]
If that is the case, do not set `webSocketFactory`, just remove it from the configuration.

**Comment by sergidt** [comment]
then, the app should work as expected?

**Comment by kum-deepak** [comment]
If you set `webSocketFactory` it takes precedence over `brokerURL`, so if you intend to use `brokerURL` you must not set `webSocketFactory`. Please check https://stomp-js.github.io/stompjs/classes/Client.html#webSocketFactory for details.

**Comment by sergidt** [comment]
ok perfect kum-deepak, let me check and I give you some feedback as soon as possible.

Thanks

**Comment by sergidt** [comment]
you were right!! all is working successfully!!

Many thanks.

**Comment by kum-deepak** [comment]
There is also https://github.com/stomp-js/ng2-stompjs which works similar to what you are trying. 

I am currently upgrading to latest stompjs version. New version is targeted in couple of weeks.

**Comment by sergidt** [comment]
which will be the good one ng2-stompjs or  @stomp/stompjs?

**Comment by kum-deepak** [comment]
I myself use ng2-stompjs, it has interesting handling for subscriptions - a call to subscribe returns an Observable. It also takes care of resubscribing in cases of reconnect - the Observable remains valid across reconnects. Unsubscribe is automatic. While publishing messages, if the underlying connection is not active, it sends when the broker connects next. It also does state management (similar to what you are doing). ng2-stompjs also adds Injectable to classes to allow the client to be injected using Angular Dependency Injection.

In this rewrite I am splitting the ng2-stompjs into rx-stomp (https://github.com/stomp-js/rx-stomp) and ng2-stompjs. rx-stomp will expose RxJS type interface to stompjs and ng2-stompjs will be a wrapper on top.

ng2-stompjs will expose rx-stomp as Angular Injectable services (which is not what you seem to be using).

If you want I will put a message when new version reaches beta.

**Comment by sergidt** [comment]
Ok thanks.

**Comment by kum-deepak** [comment]
ng2-stompjs internally uses @stomp/stompjs

In next version ng2-stompjs will use rx-stomp, which in turn will use @stomp/stompjs
